swipe:
  3:
    up:
      command: 'YDOTOOL_SOCKET="$HOME/.ydotool_socket" ydotool key 125:1 17:1 17:0 125:0'
    down:
      command: 'YDOTOOL_SOCKET="$HOME/.ydotool_socket" ydotool key 125:1 34:1 34:0 125:0'
